### ISSUE TITLE
Symfony 5, all urls are ignored

### ISSUE THREAD

**Issue by melflorance** [nelmio/NelmioCorsBundle#143] opened 2019-12-12 15:13 UTC
Hello,

I just installed the bundle with Symfony 5, there were no problems during the installation.
The default configuration was ok, until i added a query parameter to the request, and everthing is now ignored.

Here the form of the url i tried to use:
` 'http://localhost/api/users?page=1`

Im using this configuration (the default one):

```yaml
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
```

Here is the environment variable i'm using in the `.env` file:
```yaml
CORS_ALLOW_ORIGIN=^.*$
```

I tried a lot of different pattern match for the regex, i tried to remove the regex and hardcode the url, but none of them are working and i can't find any solution.

It's either that the plugin isn't supported by Symfony 5 yet, or that there is something terribly wrong.

Of course it's highly probably that my configuration is wrong, but since i'm using everthing by default and that my regex is quite largely open, i can't get it.

I would greatly appreciate if you could help me on this one.

Thanks

**Comment by rmbl** [comment] 2019-12-23 16:27
I've got the same problem on an application that I upgraded from Symfony 4.3 to 5.0. It worked while it was on Symfony 4.3.

**Comment by ChangePlaces** [comment] 2020-01-11 16:24
Can confirm, it's stopped working!

**Comment by avianez-onkologikoa** [comment] 2020-01-24 11:12
Another error, that happens when you install this module in a clean Symfony 5 proyect, it´s that this module doesn´t works... you can do this to fix it:
Add this to 'config/bundles.php' file (at the end):
`Nelmio\CorsBundle\NelmioCorsBundle::class => ['dev' => true, 'test' => true]`

**Comment by andonivianez** [comment] 2020-01-24 11:13
Another error, that happens when you install this module in a clean Symfony 5 proyect, it´s that this module doesn´t works... you can do this to fix it:
Add this to 'config/bundles.php' file (at the end):
Nelmio\CorsBundle\NelmioCorsBundle::class => ['dev' => true, 'test' => true]

**Comment by tomsihap** [comment] 2020-02-12 09:31
Same here.

**Comment by jourdan-qe** [comment] 2020-05-11 12:35
Same here. That's a pity
Are there plans to support Sf 5 on the way?
Thx

**Comment by tomsihap** [comment] 2020-07-27 09:58
Any updates on this one?

**Comment by aelfannir** [comment] 2020-09-05 09:47
Same

**Comment by aelfannir** [comment] 2020-09-15 08:30
Got the same error again with another project

**Comment by mvaljento** [comment] 2020-10-28 18:26
Same here.

**Comment by Develex** [comment] 2020-10-29 10:19
same here.

**Comment by ChangePlaces** [comment] 2020-10-30 08:38
People, let's learn what the emojis mean please. "Same here" is not constructive help.

**Comment by fd6130** [comment] 2020-11-26 10:14
I'm using this on my Symfony 5 project and so far no problem at all.

**Comment by simplis-jourdan** [comment] 2021-10-21 09:37
Hello

Well, I'm digging that topic as I'd like to use NelmioCors on Symfony 5.

So, I included last version (2.1.1) in my project and activated the module for all environments :
<img width="473" alt="Symfony modules" src="https://user-images.githubusercontent.com/85363243/138250738-703da681-3862-420d-b1c0-2223775dcac6.png">

Here is my Nelmio cors config. I voluntary set allow_methods and allow_origin in the default config. GET method is not allowed anywhere
<img width="540" alt="Nelmio cors config" src="https://user-images.githubusercontent.com/85363243/138250763-37480efc-7220-41ec-bb1f-2b21978a8790.png">

I serve Symfony with its own server on 8000 port.
And here is a curl GET request which works the same way nelmio cors would not be activated (400 response is the expected one)
<img width="485" alt="Curl request" src="https://user-images.githubusercontent.com/85363243/138250749-6e9c4293-18a1-44d8-81ec-bcf3858ced8b.png">

Despite the fact the request is allowed, I think the important thing here is there is no access-control-allow-origin headers and other cors headers in the response.
Any idea to help solve that (big) issue?

Thank you

**Comment by Seldaek** [comment] 2023-02-15 13:59
Closing here as I am not sure what the issue is. I definitely don't have problems on symfony 5 or 6. If someone still has an issue please open a new issue with repro details.

@simplis-jourdan your issue seems to be another issue entirely, you do not set an Origin header, nor a preflight OPTIONS request, so there is nothing the bundle should do.

**Closed by Seldaek** 2023-02-15 13:59 UTC

**Comment by Nincha** [comment] 2023-06-13 19:59
As it may help anyone falling back here: 

Despite the fact I was originally thinking this was a global issue with Nelmio, I found out Nelmio was working as it should and my issue was relative to [that topic](https://github.com/nelmio/NelmioCorsBundle/issues/150) instead of this one ; if I'm not mistaken this has to do with statics assets not being concerned by Nelmio.
