### ISSUE TITLE
CORS Headers not added on Exception (500 error code)

### ISSUE THREAD

**Issue by martinopic** [nelmio/NelmioCorsBundle#62] opened 2016-05-17 14:12 UTC
The bundle does not add CORS headers on error (500) response, e.g. those generetaed by FOSRestBundle

**Comment by server-may-cry** [comment] 2016-06-16 14:15
i have same problem
CORS headers [add only on master request](https://github.com/nelmio/NelmioCorsBundle/blob/master/EventListener/CorsListener.php#L53..L55)
FOSRestBundle use [sub request](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/2.0/EventListener/ExceptionListener.php#L28) to return exception response.

**Comment by lbayerl** [comment] 2016-07-07 16:09
+1

**Comment by mmeloni** [comment] 2016-08-22 15:02
+1

**Comment by hugomn** [comment] 2016-08-25 04:47
I have a curious case here. I have a POST endpoint that returns a 404 status. When the request payload is empty, the CORS header is correctly added. When it has any content ({'foo': 'bar'} for example) it's not added. Anyone has seen this?

**Comment by martinopic** [comment] 2016-08-28 20:59
I don't think CORS headers are not added to 500 response, we have an application that uses  FOSRestBundle and we got CORS headers on 500 responses. The problem, I think, is with PHP fatal errors which are not exceptions e.g. memory exceeded but, unfortunately, also NPEs. 

The only way I know of handling these errors is to register a custom function but as the script completely stop to execute when encountering a fatal error the function would be "outside symfony" and all error hadling, error rest response and cors headers should be done outside the framework inside this very single function. Not impossible but really annoying and clumsy.

Pretty much a PHP limit.

**Comment by Seldaek** [comment] 2016-08-29 10:41
Even in PHP7. not all errors are catchable unfortunately, although more are.

**Comment by samdjstevens** [comment] 2017-12-13 16:12
I'm seeing this happen (no Access-Control-Allow-Origin header present) on routes that through a `NotFoundHttpException` or doctrine exceptions. Is this expected behaviour?

**Comment by cgiacomi** [comment] 2018-03-15 12:20
I am experiencing the same problem, all NON 2xx responses don't seem to have any CORS headers. Is this normal? is there a setting I missed?

**Comment by st0at** [comment] 2020-02-12 10:58
I got the same issue, I'm using Symfony 3.4 and Nelmio Cors 1.5.6. I think this is related to: https://github.com/nelmio/NelmioCorsBundle/issues/124
@Seldaek is this issue fixed in new Nelmio Cors version 2.0.1?

**Comment by xDaizu** [comment] 2020-07-23 06:17
@st0at It is not, because I am finding this case on version 2.0.1. And it's not on a fatal error, just a regular exception thrown by the `phpoffice/phpspreadsheet` library:

```php
throw new Reader\Exception('Unable to identify a reader for this file');
```

**Comment by podorozhny** [comment] 2020-12-01 10:52
+1, annoying af

**Comment by Seldaek** [comment] 2023-02-15 13:38
Closing as duplicate of https://github.com/nelmio/NelmioCorsBundle/issues/124

**Closed by Seldaek** 2023-02-15 13:38 UTC
